ALTER TABLE core.resource_widgets
    DROP CONSTRAINT resource_widgets_pkey,
    ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ADD COLUMN area TEXT NOT NULL DEFAULT 'body'
        CHECK (area IN ('body', 'sidebar')),
    ADD COLUMN view TEXT NOT NULL DEFAULT ''
        CHECK (view = btrim(view)),
    ADD COLUMN columns INTEGER NOT NULL DEFAULT 12
        CHECK (columns BETWEEN 1 AND 12),
    ADD COLUMN margin_top INTEGER NOT NULL DEFAULT 0
        CHECK (margin_top BETWEEN 0 AND 3),
    ADD COLUMN margin_bottom INTEGER NOT NULL DEFAULT 0
        CHECK (margin_bottom BETWEEN 0 AND 3),
    ADD COLUMN enabled BOOLEAN NOT NULL DEFAULT TRUE,
    ADD CONSTRAINT resource_widgets_pkey PRIMARY KEY (id),
    ADD CONSTRAINT uq_resource_widgets_area_position
        UNIQUE (resource_id, area, position);

