ALTER TABLE core.resource_entities
    ADD COLUMN version BIGINT NOT NULL DEFAULT 1 CHECK (version > 0);

CREATE TABLE core.resource_revisions
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resource_id     BIGINT      NOT NULL,
    site_id         BIGINT      NOT NULL,
    version         BIGINT      NOT NULL CHECK (version > 0),
    kind            TEXT        NOT NULL CHECK (kind IN ('created', 'updated', 'restored')),
    source_version  BIGINT      NULL CHECK (source_version IS NULL OR source_version > 0),
    snapshot        JSONB       NOT NULL CHECK (jsonb_typeof(snapshot) = 'object'),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by      BIGINT      NULL,
    created_by_name TEXT        NOT NULL DEFAULT '',

    CONSTRAINT uq_resource_revisions_resource_version UNIQUE (resource_id, version),
    CONSTRAINT fk_resource_revisions_entity_site
        FOREIGN KEY (resource_id, site_id)
            REFERENCES core.resource_entities (id, site_id)
            ON DELETE CASCADE,
    CONSTRAINT fk_resource_revisions_created_by
        FOREIGN KEY (created_by) REFERENCES core.users (id) ON DELETE SET NULL
);

CREATE INDEX idx_resource_revisions_resource_version_desc
    ON core.resource_revisions (resource_id, version DESC);

CREATE INDEX idx_resource_revisions_site_resource_version_desc
    ON core.resource_revisions (site_id, resource_id, version DESC);
